// Code generated by ChatGPT and Copilot

#include <iostream>
#include <string>
#include "Board.h"

using namespace minesweeper;

static void printBoard(const Board& b) {
    std::cout << "   ";
    for (int c = 0; c < b.width(); ++c) std::cout << c % 10;
    std::cout << "\n";

    for (int r = 0; r < b.height(); ++r) {
        std::cout << (r % 10) << " |";
        for (int c = 0; c < b.width(); ++c) {
            const Cell& cell = b.at({r, c});
            char ch = '?';

            if (cell.isFlagged()) {
                ch = 'F';
            } else if (!cell.isRevealed()) {
                ch = '.';
            } else if (cell.isMine()) {
                ch = '*';
            } else {
                auto n = cell.adjacentMines();
                ch = (n == 0 ? ' ' : static_cast<char>('0' + n));
            }

            std::cout << ch;
        }
        std::cout << "|\n";
    }
}

int main() {
    constexpr int W = 10;
    constexpr int H = 8;
    constexpr int M = 10;

    Board board(W, H, M);

    std::cout << "Minesweeper ASCII Test\n";
    std::cout << "Commands:\n";
    std::cout << "  r x y   -> reveal cell (row x, col y)\n";
    std::cout << "  f x y   -> toggle flag\n";
    std::cout << "Example: r 3 5\n\n";

    printBoard(board);

    while (!board.isLost() && !board.isWon()) {
        std::cout << "\n> ";
        char cmd;
        int x, y;
        std::cin >> cmd >> x >> y;

        if (!std::cin.good()) break;

        if (cmd == 'r') {
            auto result = board.reveal({x, y});
            switch (result.outcome) {
                case RevealOutcome::Exploded:
                    std::cout << "BOOM! You hit a mine!\n";
                    break;
                case RevealOutcome::Won:
                    std::cout << "You WIN! 🎉\n";
                    break;
                case RevealOutcome::Revealed:
                    std::cout << result.revealed.size() << " cell(s) revealed.\n";
                    break;
                default:
                    std::cout << "No action.\n";
                    break;
            }
        } else if (cmd == 'f') {
            if (board.toggleFlag({x, y}))
                std::cout << "Flag toggled\n";
            else
                std::cout << "Nothing done\n";
        } else {
            std::cout << "Unknown command\n";
        }

        printBoard(board);
    }

    if (board.isLost()) {
        std::cout << "\n=== Game Over ===\n";
        // Reveal mines for debugging
        for (int r = 0; r < H; ++r)
            for (int c = 0; c < W; ++c)
                const_cast<Cell&>(board.at({r, c})).reveal();
        printBoard(board);
    }

    std::cout << "Bye!\n";
    return 0;
}
