// Code partly generated by ChatGPT and Copilot

#pragma once
#include <vector>
#include <cstdint>
#include <random>
#include "Cell.h"

namespace minesweeper {

struct Coord {
    int row;
    int col;
};

enum class RevealOutcome : std::uint8_t {
    Noop,     
    Revealed,  
    Exploded,   
    Won         // Last safe revealed
};

struct RevealResult {
    RevealOutcome outcome;
    std::vector<Coord> revealed; // cases révélées par cette action (propagation)
};

class Board {
public:
    // --- Constructor -------------------------------------------------------
    Board(int width, int height, int mines, std::uint64_t seed = std::random_device{}()) noexcept;

    // --- Getters const ---------------------------------------------------
    [[nodiscard]] int width()  const noexcept;
    [[nodiscard]] int height() const noexcept;
    [[nodiscard]] int mineCount() const noexcept;

    
    [[nodiscard]] bool isGenerated() const noexcept; // mines on game ?
    [[nodiscard]] bool isWon()      const noexcept;
    [[nodiscard]] bool isLost()     const noexcept;
    [[nodiscard]] int  flagsLeft()  const noexcept;

    [[nodiscard]] const Cell& at(Coord c) const noexcept;

    // --------------- Gameplay -------------------------
    RevealResult reveal(Coord c);   // reveal and propagate
    bool toggleFlag(Coord c) noexcept;

private:
    // --- Helpers intern ---------------------------------------------------
    [[nodiscard]] bool inBounds(Coord c) const noexcept;
    [[nodiscard]] std::vector<Coord> neighbors(Coord c) const;

    void generate(Coord safeStart);                    // lazy generation after first click 
    void placeMines(Coord safeStart);                  // safeStart and neighbors excluded
    void computeAdjacency();                           // for each Cell
    void propagateReveal(Coord start, RevealResult&);  // BFS

private:
    int width_;
    int height_;
    int mine_count_;
    int hidden_safe_; // safe cells hidden
    bool lost_ = false;
    bool generated_ = false;
    std::uint64_t seed_;

    std::vector<Cell> cells_; // linear board index = width*row + col 
};

} // namespace minesweeper
