// Code partly generated by ChatGPT and Copilot

#pragma once
#include <cstdint>
#include <cassert>

namespace minesweeper { // namespace minesweeper !

enum class Visibility : std::uint8_t {
    Hidden,   
    Revealed,
    Flagged  
};

// Preliminary proclamation authorizing Board to initialize/modify a Cell
class Board;


struct Cell final {
public:
    // --- Constructor -------------------------------------------------------
    constexpr Cell() noexcept : is_mine_(false), adj_mines_(0), vis_(Visibility::Hidden) {}
    // noexcept is message for compiler saying that this method doesn't throw exception.

    // --- Getters const ---------------------------------------------------
    [[nodiscard]] constexpr bool isMine()       const noexcept { return is_mine_; }
    [[nodiscard]] constexpr std::uint8_t adjacentMines() const noexcept { return adj_mines_; }
    [[nodiscard]] constexpr Visibility visibility() const noexcept { return vis_; }

    [[nodiscard]] constexpr bool isHidden()   const noexcept { return vis_ == Visibility::Hidden; }
    [[nodiscard]] constexpr bool isRevealed() const noexcept { return vis_ == Visibility::Revealed; }
    [[nodiscard]] constexpr bool isFlagged()  const noexcept { return vis_ == Visibility::Flagged; }

    // --- Change state of a cell -------------------------------------------
    /**
     * @brief Reveal a cell is Hidden (and not Flagged)
     * @return true if state changed.
     */
    bool reveal() noexcept {
        if (vis_ == Visibility::Hidden) {
            vis_ = Visibility::Revealed;
            return true;
        }
        return false;
    }

    /**
     * @brief Change Flagged <-> Hidden
     * @return true if state changed
     */
    bool toggleFlag() noexcept {
        if (vis_ == Visibility::Revealed) return false;
        vis_ = (vis_ == Visibility::Flagged) ? Visibility::Hidden : Visibility::Flagged;
        return true;
    }

private:
    // --- Mutations used only by Board ----------------
    void setMine(bool v) noexcept { is_mine_ = v; }
    void setAdjacentMines(std::uint8_t n) noexcept {
        assert(n <= 8);
        adj_mines_ = static_cast<std::uint8_t>(n & 0x0F); // 4 bits 
    }

    friend class Board;

    // --- Data ---------------------------------------
    bool            is_mine_   : 1;  // 1 bit : Mine ?
    std::uint8_t    adj_mines_ : 4;  // 0..8 (4 bits)
    Visibility      vis_       : 2;  // Hidden/Revealed/Flagged (2 bits)
};

} 
