// Code generated by ChatGPT (GameManager)

#pragma once

#include <cstdint>
#include <memory>
#include "Board.h"

namespace minesweeper {

// Forward declaration – actual implementation can be provided by
// whoever owns the timing component of the project.
class TimerManager;

/**
 * @brief High–level controller for a single Minesweeper game.
 *
 * Responsibilities:
 *  - Own the Board instance (size + mine count)
 *  - Coordinate game state: not started / playing / won / lost
 *  - React to user input (left/right clicks)
 *  - Notify / drive TimerManager (start / stop) – via well-placed hooks
 *
 * GameManager does NOT perform any rendering; it only mutates the Board
 * and exposes read-only accessors for the UI layer.
 */
class GameManager {
public:
    enum class State : std::uint8_t {
        NotStarted,
        Playing,
        Won,
        Lost
    };

    /**
     * @brief Construct a GameManager with the given board configuration.
     *
     * The actual Board is created lazily by startNewGame() so that the
     * seed can be changed between runs if desired.
     */
    GameManager(int width, int height, int mineCount,
                std::uint64_t seed = defaultSeed()) noexcept;

    /// Attach an optional TimerManager. It may be nullptr.
    void setTimerManager(TimerManager* timer) noexcept { timer_ = timer; }

    // --------------------------------------------------------------
    // Game lifecycle
    // --------------------------------------------------------------

    /// (Re)start the game with the stored configuration.
    void startNewGame();

    /// Convenience wrapper that calls startNewGame().
    void resetGame() { startNewGame(); }

    // --------------------------------------------------------------
    // Input handling
    // --------------------------------------------------------------

    /// Handle a left click (reveal cell).
    void onLeftClick(int row, int col);

    /// Handle a right click (toggle flag).
    void onRightClick(int row, int col);

    // --------------------------------------------------------------
    // State queries
    // --------------------------------------------------------------

    State state() const noexcept { return state_; }

    bool isPlaying() const noexcept { return state_ == State::Playing; }
    bool isWon()     const noexcept { return state_ == State::Won; }
    bool isLost()    const noexcept { return state_ == State::Lost; }

    bool checkWin()  const noexcept;
    bool checkLose() const noexcept { return state_ == State::Lost; }

    /// Access to the underlying Board (may be nullptr before first start).
    Board*       board()       noexcept { return board_.get(); }
    const Board* board() const noexcept { return board_.get(); }

    /// Current board dimensions / mine count (configuration values).
    int width()      const noexcept { return width_; }
    int height()     const noexcept { return height_; }
    int mineCount()  const noexcept { return mineCount_; }

    /// Change configuration for the *next* game.
    void configure(int width, int height, int mineCount,
                   std::uint64_t seed = defaultSeed()) noexcept;

    /// Random seed used to generate the board.
    std::uint64_t seed() const noexcept { return seed_; }

    /// Set a specific seed (e.g., for deterministic testing).
    void setSeed(std::uint64_t s) noexcept { seed_ = s; }

    /// Helper used by constructors and configure().
    static std::uint64_t defaultSeed() noexcept;

private:
    // Helpers (extension points if you later want to use RevealOutcome)
    void applyRevealOutcome(const Coord& clicked, RevealOutcome outcome);
    void updateWinStateAfterReveal();

    // Configuration
    int width_;
    int height_;
    int mineCount_;
    std::uint64_t seed_;

    // Owned board
    std::unique_ptr<Board> board_;

    // High-level state
    State state_ { State::NotStarted };
    bool firstClickDone_ { false };

    // Optional external timer controller (not owned)
    TimerManager* timer_ { nullptr };
};

} // namespace minesweeper
